"""Streamlit dashboard for the SaaS Security Monitoring System.

Run from the project root:
    streamlit run app.py
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import streamlit as st


ROOT_DIR = Path(__file__).resolve().parent
DATA_DIR = ROOT_DIR / "data"
RESULTS_DIR = ROOT_DIR / "results"


@st.cache_data
def load_csv(path: Path) -> pd.DataFrame:
    """Load a CSV once per dashboard refresh, with errors shown by the caller."""
    return pd.read_csv(path)


def load_project_data() -> tuple[dict[str, pd.DataFrame], list[str]]:
    """Load only generated project artifacts; do not substitute fake values."""
    paths = {
        "saas": DATA_DIR / "saas_activity.csv",
        "cloud": DATA_DIR / "cloudtrail_logs.csv",
        "shadow_it": RESULTS_DIR / "shadow_it_alerts.csv",
        "shadow_ai": RESULTS_DIR / "shadow_ai_alerts.csv",
        "cloud_alerts": RESULTS_DIR / "cloud_security_alerts.csv",
        "incidents": RESULTS_DIR / "correlated_incidents.csv",
        "comparison": RESULTS_DIR / "algorithm_comparison.csv",
    }
    data: dict[str, pd.DataFrame] = {}
    errors: list[str] = []
    for name, path in paths.items():
        if not path.exists():
            errors.append(f"Missing `{path.relative_to(ROOT_DIR)}`.")
            continue
        try:
            data[name] = load_csv(path)
        except (OSError, pd.errors.ParserError, ValueError) as exc:
            errors.append(f"Could not load `{path.relative_to(ROOT_DIR)}`: {exc}")
    return data, errors


def enrich_saas_alerts(alerts: pd.DataFrame, saas: pd.DataFrame) -> pd.DataFrame:
    """Show detected SaaS alerts together with their original application fields."""
    source_fields = ["event_id", "application", "application_category", "requests", "data_uploaded_mb", "approved"]
    return alerts.merge(saas[source_fields], on="event_id", how="left")


def enrich_cloud_alerts(alerts: pd.DataFrame, cloud: pd.DataFrame) -> pd.DataFrame:
    """Show CloudTrail context for each rule alert."""
    source_fields = ["event_id", "event_name", "resource", "source_ip", "region", "status"]
    return alerts.merge(cloud[source_fields], on="event_id", how="left")


def show_overview(data: dict[str, pd.DataFrame]) -> None:
    st.header("Overview")
    st.caption("A single view of SaaS activity, security alerts, and correlated incidents for project demonstration.")
    saas, cloud = data["saas"], data["cloud"]
    total_users = pd.concat([saas["user_id"], cloud["user_id"]]).nunique()
    high_risk = int((data["incidents"]["risk_level"] == "High").sum())
    metrics = st.columns(6)
    metrics[0].metric("Total users", total_users)
    metrics[1].metric("SaaS applications", saas["application"].nunique())
    metrics[2].metric("Shadow IT", len(data["shadow_it"]))
    metrics[3].metric("Shadow AI", len(data["shadow_ai"]))
    metrics[4].metric("Cloud alerts", len(data["cloud_alerts"]))
    metrics[5].metric("High-risk incidents", high_risk)

    st.subheader("Incident risk levels")
    risk_counts = data["incidents"]["risk_level"].value_counts().reindex(["Low", "Medium", "High"], fill_value=0)
    st.bar_chart(risk_counts)

    st.subheader("Quick Demo")
    st.caption("These are the highest-risk correlated incidents currently produced by the pipeline.")
    demo_columns = ["incident_id", "user_id", "risk_score", "risk_level", "reason"]
    st.dataframe(
        data["incidents"].sort_values("risk_score", ascending=False).head(3)[demo_columns],
        hide_index=True,
        use_container_width=True,
    )


def show_algorithm_comparison(comparison: pd.DataFrame) -> None:
    st.header("Algorithm Comparison")
    st.caption("Metrics are calculated on the common labelled holdout set generated by the project evaluation pipeline.")
    display_columns = ["method", "precision", "recall", "f1_score", "false_positive_rate"]
    st.dataframe(comparison[display_columns].round(4), hide_index=True, use_container_width=True)

    chart_path = RESULTS_DIR / "algorithm_performance.png"
    if chart_path.exists():
        st.image(str(chart_path), caption="Precision, recall, and F1-score by detection method.", use_container_width=True)
    else:
        st.bar_chart(comparison.set_index("method")[["precision", "recall", "f1_score"]])


def show_shadow_apps(data: dict[str, pd.DataFrame]) -> None:
    st.header("Shadow IT / Shadow AI")
    st.caption("Unauthorized applications are detected using the approved flag and the configurable AI application list.")
    tab_it, tab_ai = st.tabs(["Shadow IT", "Shadow AI"])
    with tab_it:
        st.dataframe(enrich_saas_alerts(data["shadow_it"], data["saas"]), hide_index=True, use_container_width=True)
    with tab_ai:
        st.dataframe(enrich_saas_alerts(data["shadow_ai"], data["saas"]), hide_index=True, use_container_width=True)


def show_cloud_security(data: dict[str, pd.DataFrame]) -> None:
    st.header("Cloud Security")
    st.caption("Rule-based CloudTrail-style alerts. One audit event may appear more than once when it violates multiple rules.")
    alerts = enrich_cloud_alerts(data["cloud_alerts"], data["cloud"])
    alert_types = sorted(alerts["alert_type"].unique())
    selected = st.multiselect("Filter by alert type", alert_types, default=alert_types)
    st.dataframe(alerts.loc[alerts["alert_type"].isin(selected)], hide_index=True, use_container_width=True)


def show_incidents(incidents: pd.DataFrame) -> None:
    st.header("Correlated Incidents")
    st.caption("Alerts are grouped by user and a 12-hour time window; IP and resource context is included where available.")
    levels = st.multiselect("Filter by risk level", ["Low", "Medium", "High"], default=["Low", "Medium", "High"])
    filtered = incidents.loc[incidents["risk_level"].isin(levels)].sort_values(["risk_score", "incident_id"], ascending=[False, True])
    st.dataframe(filtered, hide_index=True, use_container_width=True)


def show_event_details(data: dict[str, pd.DataFrame]) -> None:
    st.header("Event Details")
    st.caption("Select an alert or a correlated incident to inspect the source details used by the dashboard.")
    choice = st.radio("View", ["Alert", "Incident"], horizontal=True)
    if choice == "Alert":
        alerts = pd.concat(
            [
                data["shadow_it"].assign(source="Shadow IT"),
                data["shadow_ai"].assign(source="Shadow AI"),
                data["cloud_alerts"].assign(source="Cloud Security"),
            ],
            ignore_index=True,
        )
        labels = alerts.apply(lambda row: f"{row['source']} | {row['event_id']} | {row['alert_type']}", axis=1)
        selected_label = st.selectbox("Select alert", labels)
        selected = alerts.loc[labels == selected_label].iloc[0]
        st.json(selected.to_dict())
    else:
        incidents = data["incidents"]
        incident_id = st.selectbox("Select incident", incidents["incident_id"])
        selected = incidents.loc[incidents["incident_id"] == incident_id].iloc[0]
        st.subheader(f"{selected['incident_id']} — {selected['risk_level']} risk ({selected['risk_score']}/100)")
        st.write(selected["reason"])
        try:
            st.json(json.loads(selected["events"]))
        except (TypeError, json.JSONDecodeError):
            st.code(selected["events"])


def show_conclusion(data: dict[str, pd.DataFrame]) -> None:
    """Keep the demonstration closing summary grounded in current result files."""
    st.header("Project Conclusion")
    comparison = data["comparison"]
    best_method = comparison.loc[comparison["f1_score"].idxmax()]
    high_risk = int((data["incidents"]["risk_level"] == "High").sum())
    st.write(
        f"The monitoring pipeline detected unauthorized SaaS use, suspicious cloud activity, and {high_risk} high-risk correlated incidents."
    )
    st.write(
        f"On the current common holdout evaluation set, the Hybrid method achieved the highest F1-score ({best_method['f1_score']:.4f})."
    )
    st.caption("This comparison is specific to the generated course-project dataset and should be re-evaluated with real organizational data before operational use.")


def main() -> None:
    st.set_page_config(page_title="SaaS Security Monitoring", page_icon="🛡️", layout="wide")
    st.title("SaaS Security Monitoring and Shadow IT Detection")
    st.caption("Cloud Computing Course Project | Member 1: 231IT030 | Member 2: 231IT074")

    data, errors = load_project_data()
    if errors:
        st.error("The dashboard needs generated project artifacts before it can display results.")
        for error in errors:
            st.write(f"- {error}")
        st.code("python generate_data.py\npython evaluate.py\npython run_detections.py\npython run_correlation.py")
        return

    page = st.sidebar.radio(
        "Dashboard section",
        ["Overview", "Algorithm Comparison", "Shadow IT / Shadow AI", "Cloud Security", "Correlated Incidents", "Event Details", "Project Conclusion"],
    )
    if page == "Overview":
        show_overview(data)
    elif page == "Algorithm Comparison":
        show_algorithm_comparison(data["comparison"])
    elif page == "Shadow IT / Shadow AI":
        show_shadow_apps(data)
    elif page == "Cloud Security":
        show_cloud_security(data)
    elif page == "Correlated Incidents":
        show_incidents(data["incidents"])
    elif page == "Event Details":
        show_event_details(data)
    else:
        show_conclusion(data)


if __name__ == "__main__":
    main()
